# Generated by Django 6.0.1 on 2026-02-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_pointtransaction_rating_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
