# Generated by Django 6.0.1 on 2026-02-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_borrowrequest_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
